version: '3.8'

networks:
  indexer:
    name: indexer

services:
  redis:
    image: bitnami/redis:7.0
    container_name: indexer_redis
    networks:
      - indexer
    volumes:
      - ./data/redis:/bitnami/redis/data
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'

  mongodb:
    image: mongo:6-jammy
    container_name: indexer_mongodb
    networks:
      - indexer
    volumes:
      - ./data/mongodb:/data/db
    env_file:
      - .env
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}'
      - 'MONGO_INITDB_DATABASE=${MONGODB_DATABASE}'
